### ISSUE TITLE
Could you provides a full implementation example ?

### ISSUE THREAD

**Issue by christopherney** [eclipse-efx/efxclipse-drift#42]
Hi,

Thanks for your job, we are trying to implement DriftFX based on LWJGL example, but unfortunately it doesn't work and the source code provided by LWJGL seems not fit your documentation.

Could you add a sample project on this repo to guide us ?

Thanks

**Comment by tomsontom** [comment]
Did you see https://github.com/BestSolution-at/efxclipse-drift-samples - adding LWJGL samples in this repo is not so easy because everything we have in this repo needs get through the IP clearance at Eclipse.org so we took the fast path and provide samples through our own github account for the time being

**Comment by christopherney** [comment]
Thanks a lot @tomsontom 👍
